ModelLiquidFuels: 0 #Flag to turn or off Syn Fuel modelling capabilities - 0 - no SF, 1- SF modeled

AllowConventionalDiesel: 1
SpecifySynDieselPercentFlag: 0
percent_sf_diesel: 0

AllowConventionalJetfuel: 1
SpecifySynJetfuelPercentFlag: 0
percent_sf_jetfuel: 0

AllowConventionalGasoline: 1
SpecifySynGasolinePercentFlag: 0
percent_sf_gasoline: 0